#!/bin/bash

set -eu

GIT_REF=$(git rev-parse HEAD)
DOCKER_TAG="strapi:$GIT_REF"
# iFixit AWS ECR for strapi
REGISTRY="884681002735.dkr.ecr.us-east-1.amazonaws.com"

echo "Building docker image"
docker build -t "$DOCKER_TAG" .
docker tag "$DOCKER_TAG" "$REGISTRY/$DOCKER_TAG"
docker tag "$DOCKER_TAG" "$REGISTRY/strapi:latest"

echo "Logging into ECR..."
$(aws ecr get-login --no-include-email --region us-east-1)

echo "Pushing image..."
docker push "$REGISTRY/$DOCKER_TAG"
docker push "$REGISTRY/strapi:latest"
