#!/bin/bash

set -o pipefail -e nounset

export STRAPI_COMMIT=$(git rev-parse HEAD)

# Short circuit if the build branch is not main.
DEPLOY_BRANCH="main"
if [[ $BUILD_BRANCH != $DEPLOY_BRANCH ]]; then
   echo "Skipping $BUILD_BRANCH. We only deploy $DEPLOY_BRANCH.";
   exit 0
fi

echo "Previous deploy was $(git rev-parse last-strapi-deploy), listing backend/ changes:"
if git diff last-strapi-deploy...HEAD --exit-code --name-only -- backend/; then
   echo "No changes to the backend/ dir since then, skipping strapi deploy"
   exit 0;
fi
echo "There have been changes to the backend/ dir since then, deploying strapi at $STRAPI_COMMIT"


strapi_dir="$(git rev-parse --show-toplevel)/backend"
cd "$strapi_dir"
./build-docker-and-push

# Yes, capistrano is only available in our main repo...
# This wont be a problem when these repos are joined though :-)
cd /home/ifixit/Code
cap prod strapi:deploy

## Deploy Tag
cd "$strapi_dir"
git tag -f last-strapi-deploy "$STRAPI_COMMIT"
git push -f origin last-strapi-deploy
