import { chakra } from '@chakra-ui/react';
import SvgCrucial from './crucial.svg';
import SvgGoogle from './google.svg';
import SvgHp from './hp.svg';
import SvgLenovo from './lenovo.svg';
import SvgLogitech from './logitech.svg';
import SvgMicron from './micron.svg';
import SvgMicrosoft from './microsoft.svg';
import SvgMotorola from './motorola.svg';
import SvgNokia from './nokia.svg';
import SvgPolaroid from './polaroid.svg';
import SvgSamsung from './samsung.svg';
import SvgSteam from './steam.svg';
import SvgTeenageEngineering from './teenage-engineering.svg';
import SvgValve from './valve.svg';
import SvgVive from './vive.svg';

export const Crucial = chakra(SvgCrucial);
export const Google = chakra(SvgGoogle);
export const Hp = chakra(SvgHp);
export const Lenovo = chakra(SvgLenovo);
export const Logitech = chakra(SvgLogitech);
export const Micron = chakra(SvgMicron);
export const Microsoft = chakra(SvgMicrosoft);
export const Motorola = chakra(SvgMotorola);
export const Nokia = chakra(SvgNokia);
export const Polaroid = chakra(SvgPolaroid);
export const Samsung = chakra(SvgSamsung);
export const Steam = chakra(SvgSteam);
export const TeenageEngineering = chakra(SvgTeenageEngineering);
export const Valve = chakra(SvgValve);
export const Vive = chakra(SvgVive);
