/*
 * Auto-generated by https://app.quicktype.io/ based on the JSON from
 * https://agilbert.cominor.com/api/2.0/Guides/39258
 */
export type Guide = {
   conclusion_raw: string;
   conclusion_rendered: string;
   difficulty: string;
   documents: any[];
   flags: Flag[];
   guideid: number;
   image: ImageElement;
   introduction_raw: string;
   introduction_rendered: string;
   featured_document_embed_url: string;
   featured_document_thumbnail_url: string;
   locale: string;
   parts: Part[];
   prerequisites: any[];
   steps: Step[];
   subject: string;
   summary: string;
   time_required: string;
   time_required_min: number;
   time_required_max: number;
   title: string;
   tools: Part[];
   type: string;
   revisionid: number;
   created_date: number;
   published_date: number;
   modified_date: number;
   prereq_modified_date: number;
   public: boolean;
   comments: GuideComment[];
   category: string;
   url: string;
   patrol_threshold: number;
   can_edit: boolean;
   favorited: boolean;
   author: GuideAuthor;
   langid: string;
   featured_documentid: null;
   intro_video_url: null;
   intro_video: null;
   completed: boolean;
};

export type GuideAuthor = {
   userid: number;
   username: string;
   unique_username: string;
   join_date: number;
   image: PurpleImage;
   reputation: number;
   url: string;
   teams: number[];
};

export type PurpleImage = {
   id: number;
   guid: string;
   mini: string;
   thumbnail: string;
   '140x105': string;
   '200x150': string;
   original: string;
};

export type GuideComment = {
   commentid: number;
   locale: string;
   context: string;
   contextid: number;
   parentid: null;
   author: PurpleAuthor;
   title: string;
   text_raw: string;
   text_rendered: string;
   rating: number;
   date: number;
   modified_date: number;
   status: string;
   replies: Reply[];
};

export type PurpleAuthor = {
   userid: number;
   username: string;
   unique_username: string;
   join_date: number;
   image: FluffyImage;
   reputation: number;
   url: string;
   teams: any[];
};

export type FluffyImage = {
   id: number;
   guid: string;
   mini: string;
   thumbnail: string;
   medium: string;
   original: string;
};

export type Reply = {
   commentid: number;
   locale: string;
   context: string;
   contextid: number;
   parentid: number;
   author: GuideAuthor;
   title: string;
   text_raw: string;
   text_rendered: string;
   rating: number;
   date: number;
   modified_date: number;
   status: string;
};

export type Flag = {
   title: string;
   flagid: string;
   text: string;
};

export type ImageElement = {
   id: number;
   guid: string;
   mini: string;
   thumbnail: string;
   '140x105': string;
   '200x150': string;
   standard: string;
   '440x330': string;
   medium: string;
   large: string;
   huge?: string;
   original: string;
};

export type Part = {
   text: string;
   notes: null;
   type: string;
   quantity: number;
   url: string;
   thumbnail: null | string;
   isoptional: boolean;
};

export type Step = {
   title: string;
   lines: Line[];
   guideid: number;
   stepid: number;
   orderby: number;
   revisionid: number;
   media: Media;
   comments: StepComment[];
};

export type StepComment = {
   commentid: number;
   locale: string;
   context: string;
   contextid: number;
   parentid: null;
   author: FluffyAuthor;
   title: string;
   text_raw: string;
   text_rendered: string;
   rating: number;
   date: number;
   modified_date: number;
   status: string;
   replies: any[];
};

export type FluffyAuthor = {
   userid: number;
   username: string;
   unique_username: string;
   join_date: number;
   image: ImageElement;
   reputation: number;
   url: string;
   teams: any[];
};

export type Line = {
   text_raw: string;
   bullet: Bullet;
   level: number;
   lineid: null;
   text_rendered: string;
};

export type Bullet = 'black' | 'red' | 'blue' | 'green' | 'yellow';

export type Media = {
   type: string;
   data: ImageElement[];
};
