const links = {
   COMMUNITY: 'https://www.ifixit.com/Community',
   LEADERBOARD: 'https://www.ifixit.com/Leaderboard',
   ALL_TEAMS: 'https://www.ifixit.com/Teams/all',
   BUSINESS: 'https://www.ifixit.com/Business',
   CONTRIBUTE: 'https://www.ifixit.com/Contribute',
   TRANSLATE: 'https://www.ifixit.com/Translate',
   PATROL: 'https://www.ifixit.com/Patrol',
   MODERATION: 'https://www.ifixit.com/Moderation',
   USE_GUIDELINES: 'https://www.ifixit.com/Info/Use_Guidelines',
   ANSWERS: 'https://www.ifixit.com/Answers',
   NEW: 'https://www.ifixit.com/New',
   GUIDE_NEW: 'https://www.ifixit.com/Guide/new',
   ABOUT_US: 'https://www.ifixit.com/Info/index',
   NEWSLETTER: 'https://www.ifixit.com/Newsletter',
   HELP: 'https://help.ifixit.com/',
   CAREERS: 'https://www.ifixit.com/about-us/careers',
   FEEDBACK: 'https://meta.ifixit.com/',
   API: 'https://www.ifixit.com/api/2.0/doc',
   PRESS: 'https://www.ifixit.com/Info/Media',
   NEWS: 'https://www.ifixit.com/News/all-categories',
   PRO: 'https://pro.ifixit.com/',
   RETAIL_LOCATOR: 'https://www.ifixit.com/Retail',
   MANUFACTURERS: 'https://www.ifixit.com/Page/Services',
   FACEBOOK: 'https://facebook.com/ifixit',
   TWITTER: 'https://twitter.com/ifixit',
   TIKTOK: 'https://tiktok.com/@ifixit.com',
   YOUTUBE: 'https://www.youtube.com/user/iFixitYourself',
   INSTAGRAM: 'https://www.instagram.com/ifixit/',
   REPAIR_ORG: 'https://www.repair.org/',
   LICENSING: 'https://www.ifixit.com/Info/Licensing',
   PRIVACY: 'https://www.ifixit.com/Info/Privacy',
   TERMS_OF_USE: 'https://www.ifixit.com/Info/Terms_of_Use',
   LOGIN: 'https://www.ifixit.com/login',
};

export default links;
